INFO 2025-02-26 22:12:57,302 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 22:13:00,330 basehttp "GET / HTTP/1.1" 200 3228
WARNING 2025-02-26 22:13:00,471 log Not Found: /favicon.ico
WARNING 2025-02-26 22:13:00,471 basehttp "GET /favicon.ico HTTP/1.1" 404 4429
INFO 2025-02-26 22:13:01,963 basehttp "GET /book/1/ HTTP/1.1" 200 1273
INFO 2025-02-26 22:13:40,396 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\views.py changed, reloading.
INFO 2025-02-26 22:13:40,675 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 22:13:42,510 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-02-26 22:13:44,532 basehttp "GET /book/1/ HTTP/1.1" 200 1330
INFO 2025-02-26 22:13:46,675 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-02-26 22:14:55,297 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\views.py changed, reloading.
INFO 2025-02-26 22:14:55,598 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 22:14:59,226 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-02-26 22:15:00,746 basehttp "GET /book/1/ HTTP/1.1" 200 1330
WARNING 2025-02-26 22:15:32,987 log Not Found: /book/update/
WARNING 2025-02-26 22:15:32,987 basehttp "GET /book/update/ HTTP/1.1" 404 4432
WARNING 2025-02-26 22:15:36,730 log Not Found: /book/update/1
WARNING 2025-02-26 22:15:36,731 basehttp "GET /book/update/1 HTTP/1.1" 404 4437
WARNING 2025-02-26 22:16:05,821 log Not Found: /admin
WARNING 2025-02-26 22:16:05,822 basehttp "GET /admin HTTP/1.1" 404 4405
INFO 2025-02-26 22:16:09,520 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-02-26 22:19:55,760 basehttp "GET /book/1/ HTTP/1.1" 200 1330
INFO 2025-02-26 22:19:57,095 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-02-26 22:20:00,649 basehttp "GET /logout/ HTTP/1.1" 302 0
INFO 2025-02-26 22:20:00,702 basehttp "GET /login/ HTTP/1.1" 200 2812
INFO 2025-02-26 22:20:09,677 basehttp "POST /login/ HTTP/1.1" 302 0
INFO 2025-02-26 22:20:09,682 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-03-03 21:31:26,584 autoreload Watching for file changes with StatReloader
INFO 2025-03-03 21:31:28,018 basehttp "GET / HTTP/1.1" 200 3228
WARNING 2025-03-03 21:31:28,208 log Not Found: /favicon.ico
WARNING 2025-03-03 21:31:28,208 basehttp "GET /favicon.ico HTTP/1.1" 404 4429
INFO 2025-03-03 21:31:29,733 basehttp "GET /book/1/ HTTP/1.1" 200 1330
INFO 2025-03-03 21:31:31,876 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-03-03 21:31:45,096 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-03-03 21:31:46,955 basehttp "GET /book/1/ HTTP/1.1" 200 1330
INFO 2025-03-03 21:31:49,820 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-03-03 21:31:49,922 basehttp "GET / HTTP/1.1" 200 3228
INFO 2025-03-03 21:31:52,442 basehttp "GET /book/1/ HTTP/1.1" 200 1330
INFO 2025-03-03 21:31:58,097 basehttp "GET /admin/auth/group/1/change/ HTTP/1.1" 200 13046
INFO 2025-03-03 21:31:58,139 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:31:58,247 basehttp - Broken pipe from ('127.0.0.1', 52404)
INFO 2025-03-03 21:31:58,254 basehttp - Broken pipe from ('127.0.0.1', 52403)
INFO 2025-03-03 21:31:58,260 basehttp - Broken pipe from ('127.0.0.1', 52402)
INFO 2025-03-03 21:31:58,265 basehttp - Broken pipe from ('127.0.0.1', 52397)
INFO 2025-03-03 21:31:58,293 basehttp - Broken pipe from ('127.0.0.1', 52398)
INFO 2025-03-03 21:31:58,306 basehttp - Broken pipe from ('127.0.0.1', 52405)
INFO 2025-03-03 21:32:04,292 basehttp "GET /admin/auth/group/1/change/ HTTP/1.1" 200 13046
INFO 2025-03-03 21:32:04,306 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-03 21:32:04,313 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-03 21:32:04,314 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-03 21:32:04,315 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-03 21:32:04,316 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-03 21:32:04,317 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 200 8794
INFO 2025-03-03 21:32:04,329 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-03 21:32:04,331 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-03-03 21:32:04,332 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-03 21:32:04,332 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-03 21:32:04,334 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-03 21:32:04,336 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
INFO 2025-03-03 21:32:04,345 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-03 21:32:04,346 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-03 21:32:04,346 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15502
INFO 2025-03-03 21:32:04,347 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-03-03 21:32:04,352 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:32:04,359 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-03 21:32:04,380 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-03 21:32:04,395 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-03-03 21:32:04,407 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-03 21:32:04,438 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-03 21:32:04,487 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-03 21:32:04,487 basehttp "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2025-03-03 21:32:04,487 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-03-03 21:32:04,487 basehttp "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2025-03-03 21:32:08,670 basehttp "GET /admin/books/book/add/ HTTP/1.1" 200 13422
INFO 2025-03-03 21:32:08,686 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:32:08,700 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-03-03 21:32:08,703 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-03-03 21:32:08,708 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-03-03 21:32:08,712 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-03 21:32:08,736 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-03-03 21:33:03,327 basehttp "POST /admin/books/book/add/ HTTP/1.1" 302 0
INFO 2025-03-03 21:33:03,374 basehttp "GET /admin/books/book/ HTTP/1.1" 200 11379
INFO 2025-03-03 21:33:03,392 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:33:03,392 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-03 21:33:03,402 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-03 21:33:03,410 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-03 21:33:03,410 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-03-03 21:33:08,025 basehttp "GET / HTTP/1.1" 200 3903
INFO 2025-03-03 21:33:08,053 basehttp "GET /book_covers/sample.jpg HTTP/1.1" 200 34256
INFO 2025-03-03 21:33:50,630 autoreload Watching for file changes with StatReloader
INFO 2025-03-03 21:33:55,245 basehttp "GET / HTTP/1.1" 200 4121
INFO 2025-03-03 21:33:55,259 basehttp "GET /book_covers/sample.jpg HTTP/1.1" 304 0
INFO 2025-03-03 21:34:02,528 basehttp "GET /admin/books/book/add/ HTTP/1.1" 200 13422
INFO 2025-03-03 21:34:02,542 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:35:28,726 basehttp "POST /admin/books/book/add/ HTTP/1.1" 200 13792
INFO 2025-03-03 21:35:28,739 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:35:52,457 basehttp "POST /admin/books/book/add/ HTTP/1.1" 302 0
INFO 2025-03-03 21:35:52,465 basehttp "GET /admin/books/book/add/ HTTP/1.1" 200 13654
INFO 2025-03-03 21:35:52,480 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:36:27,504 basehttp "POST /admin/books/book/add/ HTTP/1.1" 302 0
INFO 2025-03-03 21:36:27,513 basehttp "GET /admin/books/book/add/ HTTP/1.1" 200 13655
INFO 2025-03-03 21:36:27,526 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:36:59,710 basehttp "POST /admin/books/book/add/ HTTP/1.1" 200 13737
INFO 2025-03-03 21:36:59,724 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:37:07,515 basehttp "POST /admin/books/book/add/ HTTP/1.1" 200 13652
INFO 2025-03-03 21:37:07,528 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-03 21:37:15,383 basehttp "GET / HTTP/1.1" 200 5554
INFO 2025-03-03 21:37:15,404 basehttp "GET /book_covers/sample.jpg HTTP/1.1" 304 0
INFO 2025-03-03 21:37:15,462 basehttp "GET /book_covers/Book-cover-page-3-CRC.webp HTTP/1.1" 200 15012
INFO 2025-03-03 21:37:15,467 basehttp "GET /book_covers/business-book-cover-design-template-e8b0585ed1cce8c483170582c0f9f3ff_screen.jpg HTTP/1.1" 200 56134
INFO 2025-03-03 21:39:02,606 autoreload Watching for file changes with StatReloader
INFO 2025-03-03 21:41:09,985 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\views.py changed, reloading.
INFO 2025-03-03 21:41:10,260 autoreload Watching for file changes with StatReloader
INFO 2025-03-03 21:41:58,303 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\views.py changed, reloading.
INFO 2025-03-03 21:41:58,596 autoreload Watching for file changes with StatReloader
INFO 2025-03-03 21:42:08,358 basehttp "GET / HTTP/1.1" 200 5554
INFO 2025-03-03 21:42:08,375 basehttp "GET /book_covers/sample.jpg HTTP/1.1" 304 0
INFO 2025-03-03 21:42:08,375 basehttp "GET /book_covers/Book-cover-page-3-CRC.webp HTTP/1.1" 304 0
INFO 2025-03-03 21:42:08,376 basehttp "GET /book_covers/business-book-cover-design-template-e8b0585ed1cce8c483170582c0f9f3ff_screen.jpg HTTP/1.1" 304 0
INFO 2025-03-12 21:31:29,714 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:33:09,276 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\admin.py changed, reloading.
INFO 2025-03-12 21:33:14,073 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:34:47,059 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:35:09,828 autoreload Watching for file changes with StatReloader
ERROR 2025-03-12 21:35:19,372 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-03-12 21:35:19,376 basehttp "GET / HTTP/1.1" 500 125111
WARNING 2025-03-12 21:35:19,611 log Not Found: /favicon.ico
WARNING 2025-03-12 21:35:19,612 basehttp "GET /favicon.ico HTTP/1.1" 404 3655
INFO 2025-03-12 21:36:29,351 autoreload Watching for file changes with StatReloader
ERROR 2025-03-12 21:36:30,534 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: books_book.isbn

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: books_book.isbn
ERROR 2025-03-12 21:36:30,540 basehttp "GET / HTTP/1.1" 500 196294
INFO 2025-03-12 21:39:27,396 autoreload Watching for file changes with StatReloader
ERROR 2025-03-12 21:39:28,659 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\mixins.py", line 72, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\mixins.py", line 51, in handle_no_permission
    resolved_login_url = resolve_url(self.get_login_url())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-03-12 21:39:28,660 basehttp "GET / HTTP/1.1" 500 90571
INFO 2025-03-12 21:40:17,809 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\urls.py changed, reloading.
INFO 2025-03-12 21:40:18,105 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:41:33,768 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\bookproject\settings.py changed, reloading.
INFO 2025-03-12 21:41:34,026 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:42:18,827 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:42:29,804 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:43:15,623 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:43:17,400 basehttp "GET / HTTP/1.1" 302 0
ERROR 2025-03-12 21:43:17,431 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-03-12 21:43:17,433 basehttp "GET /login/?next=/ HTTP/1.1" 500 81854
INFO 2025-03-12 21:46:08,914 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:46:11,505 basehttp "GET / HTTP/1.1" 302 0
ERROR 2025-03-12 21:46:11,558 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
ERROR 2025-03-12 21:46:11,562 basehttp "GET /login/?next=/ HTTP/1.1" 500 116576
INFO 2025-03-12 21:47:02,785 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:47:03,827 basehttp "GET / HTTP/1.1" 302 0
ERROR 2025-03-12 21:47:03,851 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base_generic.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base_generic.html
ERROR 2025-03-12 21:47:03,853 basehttp "GET /login/?next=/ HTTP/1.1" 500 129891
INFO 2025-03-12 21:47:24,956 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 21:47:27,557 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-03-12 21:47:27,646 basehttp "GET /login/?next=/ HTTP/1.1" 200 908
INFO 2025-03-12 21:47:39,778 basehttp "POST /login/?next=/ HTTP/1.1" 200 1064
INFO 2025-03-24 21:25:26,290 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 21:36:13,516 autoreload Watching for file changes with StatReloader
ERROR 2025-03-24 21:36:16,433 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\mixins.py", line 72, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\mixins.py", line 51, in handle_no_permission
    resolved_login_url = resolve_url(self.get_login_url())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GComp.ge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-03-24 21:36:16,436 basehttp "GET / HTTP/1.1" 500 90467
WARNING 2025-03-24 21:36:16,657 log Not Found: /favicon.ico
WARNING 2025-03-24 21:36:16,657 basehttp "GET /favicon.ico HTTP/1.1" 404 3918
INFO 2025-03-24 21:38:10,190 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 21:38:11,285 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-03-24 21:38:11,424 basehttp "GET /accounts/login/?next=/ HTTP/1.1" 200 908
INFO 2025-03-24 21:38:37,585 basehttp "POST /accounts/login/?next=/ HTTP/1.1" 200 1064
INFO 2025-03-24 21:39:30,772 basehttp "GET /api/books/?page=1&page_size=5 HTTP/1.1" 200 8779
INFO 2025-03-24 21:39:30,918 basehttp "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2025-03-24 21:39:30,920 basehttp "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
INFO 2025-03-24 21:39:30,923 basehttp "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2025-03-24 21:39:30,924 basehttp "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2025-03-24 21:39:30,926 basehttp "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2025-03-24 21:39:30,928 basehttp "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
INFO 2025-03-24 21:39:30,959 basehttp "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
INFO 2025-03-24 21:39:30,966 basehttp "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
INFO 2025-03-24 21:39:30,972 basehttp "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
INFO 2025-03-24 21:39:30,975 basehttp "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2025-03-24 21:39:30,976 basehttp "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2025-03-24 21:39:30,993 basehttp "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2025-03-24 21:39:31,003 basehttp "GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
INFO 2025-03-24 21:51:56,219 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 21:55:46,671 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 21:57:26,613 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\urls.py changed, reloading.
INFO 2025-03-24 21:57:26,994 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 21:58:43,281 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:02:40,403 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:07:49,533 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:07:51,633 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-03-24 22:07:51,644 basehttp "GET /accounts/login/?next=/ HTTP/1.1" 200 908
INFO 2025-03-24 22:08:25,391 autoreload C:\Users\GComp.ge\Desktop\django\bookproject\books\urls.py changed, reloading.
INFO 2025-03-24 22:08:25,775 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:10:38,393 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:10:42,841 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-03-24 22:10:42,851 basehttp "GET /accounts/login/?next=/ HTTP/1.1" 200 908
INFO 2025-03-24 22:11:02,686 basehttp "GET /swagger/ HTTP/1.1" 200 2211
INFO 2025-03-24 22:11:02,862 basehttp "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
INFO 2025-03-24 22:11:02,865 basehttp "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
INFO 2025-03-24 22:11:02,879 basehttp "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
INFO 2025-03-24 22:11:02,890 basehttp "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
INFO 2025-03-24 22:11:02,892 basehttp "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
INFO 2025-03-24 22:11:02,896 basehttp "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
INFO 2025-03-24 22:11:02,900 basehttp "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
INFO 2025-03-24 22:11:03,052 basehttp "GET /swagger/?format=openapi HTTP/1.1" 200 369
INFO 2025-03-24 22:11:03,083 basehttp "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
INFO 2025-03-24 22:13:42,526 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:14:37,455 autoreload Watching for file changes with StatReloader
INFO 2025-03-24 22:14:39,473 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-03-24 22:14:39,482 basehttp "GET /accounts/login/?next=/ HTTP/1.1" 200 908
WARNING 2025-03-24 22:14:44,764 log Not Found: /swagger
WARNING 2025-03-24 22:14:44,765 basehttp "GET /swagger HTTP/1.1" 404 5195
INFO 2025-03-24 22:15:09,455 basehttp "GET /swagger/ HTTP/1.1" 200 2211
INFO 2025-03-24 22:15:09,474 basehttp "GET /static/drf-yasg/style.css HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,481 basehttp "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,482 basehttp "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,482 basehttp "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,483 basehttp "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,483 basehttp "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,484 basehttp "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
INFO 2025-03-24 22:15:09,629 basehttp "GET /swagger/?format=openapi HTTP/1.1" 200 808
